[package]
name = "rbq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ricq-axum-api = { path = "ricq/examples/ricq-axum-api"}
